### ISSUE TITLE
Trying to Set a Role as Owner for Bot, Will not work

### ISSUE THREAD

**Issue by ghost** [raluvy95/jolly#16]
Hello,

I'm trying to set a Role as an owner in the configuration file, so anyone who is assigned that role can use the command. I put in the Role ID, and it doesn't recognize it, it seems. The command still works, but it wont let me execute the command, even with the role assigned

**Comment by raluvy95** [comment]
The `owners` parameter in configuration file only accepts User ID.

[jump to code](https://github.com/raluvy95/jolly/blob/master/src/classes/command.ts#L113)
