### ISSUE TITLE
Forked Bot - Bot Continues Restarting

### ISSUE THREAD

**Issue by ghost** [raluvy95/jolly#6]
Hello, Im getting some issues with my bot, which was forked from this project. The Issue Im getting is that it keeps restarting every 4-5 Hours. It doesnt report a fatal error, it just restarts. Im running this on a machine with 16GB, but i doubt thats the reason

**Comment by raluvy95** [comment]
I don't know what's happening because it never happened to me, but there are two possible reasons:

1. Your internet went off for few seconds which causes WebSocket to hang out and trying to restart the server.
2. Your server probably has a restart schedule.

**Comment by ghost** [comment]
So, the bot is running on my Mac without a Restart Schedule...The Internet issue could very well be the reason for it restarting, but its weird that it does that at a consistent rate (i narrowed it down to about 4 1/2 hours)

**Comment by raluvy95** [comment]
That's weird anyway. Unfortunately, I am unable to find out what's going on.

Since the bot is running on MacOS, could you try it on Linux, specifically Ubuntu or Arch? If it doesn't constantly restarts on linux, then there's something went wrong on MacOS.

**Comment by ghost** [comment]
yeah i can try to see if thats the issue

**Comment by ghost** [comment]
Ok, so it is still wanting to restart

**Comment by raluvy95** [comment]
After 1 hour of running? That's rather odd to me. Sorry, but there's no solution for this as it never occurs for me. I'll leave this issue opened if anyone is having same issue.

**Comment by ghost** [comment]
Ok. Imma try testing the config and see if anything is messed up

**Comment by raluvy95** [comment]
The issue solved. He was using pm2 instead of screen. I'll write a documentation about how to keep the bot online 24/7

**Comment by ghost** [comment]
Ok Sweet Thank You
